<a href="https://colab.research.google.com/github/aadithya-vimal/SamsungInnovationCampus/blob/main/numpy_practice_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Sample programs for numpy array basics
import numpy as np
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr2 = np.linspace(0,20,5)
print(arr2)

[ 0.  5. 10. 15. 20.]


In [5]:
arr3 = [5,10,15,20]
arr3[1] = 100
print(arr3)

[5, 100, 15, 20]


In [6]:
arr4 = [[1,2,3],[4,5,6]]
print(f"First array(2x3) = {arr4}")
arr5 = [10,20,30]
arr4[1] = arr5
print(f"Second array(1x3) = {arr4}")
summedArray = arr4 + arr5
print(summedArray)

First array(2x3) = [[1, 2, 3], [4, 5, 6]]
Second array(1x3) = [[1, 2, 3], [10, 20, 30]]
[[1, 2, 3], [10, 20, 30], 10, 20, 30]


In [7]:
arr6 = [1,2,3]
arr7 = arr6
arr7[0] = 1000
print(arr6)

[1000, 2, 3]


In [8]:
arr8 = [1,2,3]
arr9 = arr8.copy()
arr9[0] = 1000
print(arr9)
print(arr8)

[1000, 2, 3]
[1, 2, 3]


In [17]:
arr10 = np.linspace(0,11,12)
arr11 = arr10.reshape((3,4))
arr12 = arr10.reshape((2,6))
print(arr10)
print(arr11)
print(arr12)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]


In [24]:
arr13 = np.array([1,2.5,3])
arr14 = arr13.astype('int')
print(f"The array before conversion: {arr13}")
print(f"The array after conversion: {arr14}")

The array before conversion: [1.  2.5 3. ]
The array after conversion: [1 2 3]


In [39]:
arr15 = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
print(f"Array after deletion: {np.delete(arr15, 0, axis = None)}")

Array after deletion: [ 1  2  3  4  5  6  7  8  9 10 11]


In [41]:
ad=np.array([[[1,2],[3,4],[4,5]],[[2,1],[3,6],[2,8]]])
print(f"Size of array: {ad.size}")
print(f"Shape of array: {ad.shape}")
print(f"Length of array: {len(ad)}")
print(f"Number of dimensions: {ad.ndim}")

Size of array: 12
Shape of array: (2, 3, 2)
Length of array: 2
Number of dimensions: 3


In [42]:
ae=(np.linspace(0,11,12))
af=(np.arange(0,11))
print(ae)
print(af)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 0  1  2  3  4  5  6  7  8  9 10]
