<a href="https://colab.research.google.com/github/aadithya-vimal/SamsungInnovationCampus/blob/main/MatrixFunction%26Differentiation_10_4_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic matrix operations

In [ ]:
#Creating a simple matrix
matrix = [
    [1, 2],
    [3, 4]
]
print(matrix)

[[1, 2], [3, 4]]


In [ ]:
import numpy as np

print("--- Creating Arrays ---")
# Create a 2x3 array of zeros
zeros_array = np.zeros((2, 3))
print("Zeros Array:\n", zeros_array)

# Create a 3x2 array of ones
ones_array = np.ones((3, 2))
print("\nOnes Array:\n", ones_array)

# Create a 2x2 array with random values between 0 and 1
rand_array = np.random.rand(2, 2)
print("\nRandom Array (2x2):\n", rand_array)

# Create a 2x2 array with random values integers
rand_array2 = np.random.randint(1,10,(2, 2))
print("\nRandom Array with random values integers(2x2):\n", rand_array2)

# Create a 2x2 array with random values normal form
rand_array3 = np.random.randn(2, 2)
print("\nRandom Array with random values normal form(2x2):\n", rand_array3)

# Create another 2x2 array for operations
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6], [7, 8]])
print("\nArray A:\n", array_a)
print("\nArray B:\n", array_b)

print("\n--- Matrix Operations ---")
# Transpose
transposed_a = array_a.T
print("\nTranspose of A:\n", transposed_a)

# Dot product using np.dot()
dot_product = np.dot(array_a, array_b)
print("\nDot Product (A . B) using np.dot():\n", dot_product)

# Matrix multiplication using @ operator
matrix_mult = array_a @ array_b
print("\nMatrix Multiplication (A @ B) using @ operator:\n", matrix_mult)
print("\nMatrix Multiplication using np.matmul() operator:\n", np.matmul(array_a, array_b))

# Element-wise Addition
addition = array_a + array_b
print("\nElement-wise Addition (A + B):\n", addition)

# Element-wise Subtraction
subtraction = array_a - array_b
print("\nElement-wise Subtraction (A - B):\n", subtraction)

# Element-wise Multiplication
multiplication = array_a * array_b
print("\nElement-wise Multiplication (A * B):\n", multiplication)

--- Creating Arrays ---
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Random Array (2x2):
 [[0.94574884 0.84795392]
 [0.99423189 0.65047684]]

Random Array with random values integers(2x2):
 [[5 7]
 [9 7]]

Random Array with random values normal form(2x2):
 [[-1.34932832  0.40266132]
 [-1.96027969 -0.63688883]]

Array A:
 [[1 2]
 [3 4]]

Array B:
 [[5 6]
 [7 8]]

--- Matrix Operations ---

Transpose of A:
 [[1 3]
 [2 4]]

Dot Product (A . B) using np.dot():
 [[19 22]
 [43 50]]

Matrix Multiplication (A @ B) using @ operator:
 [[19 22]
 [43 50]]

Matrix Multiplication using np.matmul() operator:
 [[19 22]
 [43 50]]

Element-wise Addition (A + B):
 [[ 6  8]
 [10 12]]

Element-wise Subtraction (A - B):
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]


In [ ]:
import numpy as np

print("Enter elements for Matrix 1 (3x3). Each row should have 3 space-separated numbers.")
matrix1_rows = []
for i in range(3):
    row_str = input(f"Enter row {i+1} for Matrix 1: ")
    matrix1_rows.append(list(map(int, row_str.split())))
matrix1 = np.array(matrix1_rows)
print(f"\nMatrix 1:\n{matrix1}")

print("\nEnter elements for Matrix 2 (3x3). Each row should have 3 space-separated numbers.")
matrix2_rows = []
for i in range(3):
    row_str = input(f"Enter row {i+1} for Matrix 2: ")
    matrix2_rows.append(list(map(int, row_str.split())))
matrix2 = np.array(matrix2_rows)
print(f"\nMatrix 2:\n{matrix2}")

product_matrix = np.dot(matrix1, matrix2)
print(f"\nProduct of Matrix 1 and Matrix 2:\n{product_matrix}")

transposed_product = product_matrix.T
print(f"\nTransposed Product Matrix:\n{transposed_product}")

Enter elements for Matrix 1 (3x3). Each row should have 3 space-separated numbers.
Enter row 1 for Matrix 1: 4 5 6
Enter row 2 for Matrix 1: 1 2 5
Enter row 3 for Matrix 1: 3 4 8

Matrix 1:
[[4 5 6]
 [1 2 5]
 [3 4 8]]

Enter elements for Matrix 2 (3x3). Each row should have 3 space-separated numbers.
Enter row 1 for Matrix 2: 2 5 9
Enter row 2 for Matrix 2: 7 8 9
Enter row 3 for Matrix 2: 5 6 8

Matrix 2:
[[2 5 9]
 [7 8 9]
 [5 6 8]]

Product of Matrix 1 and Matrix 2:
[[ 73  96 129]
 [ 41  51  67]
 [ 74  95 127]]

Transposed Product Matrix:
[[ 73  41  74]
 [ 96  51  95]
 [129  67 127]]


In [ ]:
n = int(input("Enter the size of the square matrix (n): "))
matrix = []
print(f"Enter {n} rows for the {n}x{n} matrix, with elements separated by spaces:")
for i in range(n):
    while True:
        row_str = input(f"Enter row {i + 1} (expecting {n} numbers separated by spaces): ")
        row = list(map(int, row_str.split()))
        if len(row) == n:
            matrix.append(row)
            break
        else:
            print(f"Error: You entered {len(row)} numbers. Please enter exactly {n} numbers for this row.")

print("Your square matrix:")
for r in matrix:
    print(r)

Enter the size of the square matrix (n): 3
Enter 3 rows for the 3x3 matrix, with elements separated by spaces:
Enter row 1 (expecting 3 numbers separated by spaces): 1 2 3
Enter row 2 (expecting 3 numbers separated by spaces): 4 5 6
Enter row 3 (expecting 3 numbers separated by spaces): 7 8 9
Your square matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [ ]:
import numpy as np

n = int(input("Enter the size for the unit matrix: "))
unit_matrix = np.eye(n)

print(f"Unit matrix of size {n}x{n}:")
print(unit_matrix)

Enter the size for the unit matrix: 2
Unit matrix of size 2x2:
[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np

n = int(input("Enter the size of the symmetric matrix (n): "))
symmetric_matrix = np.zeros((n, n), dtype=int)

print("Enter elements for the upper triangle (including diagonal) row by row:")
for i in range(n):
    for j in range(i, n):
        value = int(input(f"Enter element M[{i+1}][{j+1}]: "))
        symmetric_matrix[i, j] = value
        symmetric_matrix[j, i] = value # Set the symmetric element

print("\nYour Symmetric Matrix:")
print(symmetric_matrix)

Enter the size of the symmetric matrix (n): 2
Enter elements for the upper triangle (including diagonal) row by row:
Enter element M[1][1]: 1
Enter element M[1][2]: 2
Enter element M[2][2]: 3

Your Symmetric Matrix:
[[1 2]
 [2 3]]


In [ ]:
import numpy as np

# Example matrix (you can replace this with your own matrix)
my_matrix = [[1, 2, 3], [2, 4, 5], [3, 5, 6]] # This one is symmetric
# my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # This one is not symmetric

np_matrix = np.array(my_matrix)

print("Your matrix:")
print(np_matrix)

if np_matrix.shape[0] != np_matrix.shape[1]:
    print("The matrix is not square, so it cannot be symmetric.")
elif np.array_equal(np_matrix, np_matrix.T):
    print("The matrix is symmetric.")
else:
    print("The matrix is NOT symmetric.")

Your matrix:
[[1 2 3]
 [2 4 5]
 [3 5 6]]
The matrix is symmetric.


In [ ]:
import numpy as np

# Define a matrix (must be square and non-singular)
matrix_to_invert = np.array([[1, 2], [3, 4]])

print("Original matrix:\n", matrix_to_invert)

# Calculate the inverse
inverse_matrix = np.linalg.inv(matrix_to_invert)

print("\nInverse matrix:\n", inverse_matrix)

Original matrix:
 [[1 2]
 [3 4]]

Inverse matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np

# Define a matrix (you can change this to any square matrix)
my_matrix = np.array([
    [1, 2],
    [3, 4]
])

print("Original matrix:\n", my_matrix)

# Calculate the determinant
determinant = np.linalg.det(my_matrix)

print("\nDeterminant of the matrix:", determinant)

Original matrix:
 [[1 2]
 [3 4]]

Determinant of the matrix: -2.0000000000000004


# Eigen vectors and Eigen values

### Explanation of Eigenvalues and Eigenvectors

-   **Eigenvalues** are special scalar values associated with a linear system of equations. They are often represented by the Greek letter lambda (λ).

-   **Eigenvectors** are special non-zero vectors that only change by a scalar factor (the eigenvalue) when a linear transformation (like multiplying by a matrix) is applied to them. When you multiply a matrix A by its eigenvector v, you get the same eigenvector back, scaled by the eigenvalue λ (i.e., Av = λv).

-   In the output from the code cell above, the first array (`eigenvalues`) contains the scalar eigenvalues. The second array (`eigenvectors`) contains the corresponding eigenvectors, where each column is an eigenvector linked to the eigenvalue at the same index in the `eigenvalues` array.

In [ ]:
import numpy as np

# Define a sample square matrix
# You can change this matrix to any square matrix you like
matrix = np.array([
    [4, 2],
    [1, 3]
])

print("Original Matrix:")
print(matrix)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors (each column corresponds to an eigenvalue):")
print(eigenvectors)

Original Matrix:
[[4 2]
 [1 3]]

Eigenvalues:
[5. 2.]

Eigenvectors (each column corresponds to an eigenvalue):
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


# Differentiation


In [ ]:
import sympy

print("--- Symbolic Differentiation (using SymPy) ---")

# Define the variables as symbols
x, k = sympy.symbols('x k')

# Function 1: x^2 - 3k
f1_sym = x**2 - 3*k
derivative_f1_sym = sympy.diff(f1_sym, x)
print(f"Original function 1: f(x) = {f1_sym}")
print(f"First derivative of f1 with respect to x: f'(x) = {derivative_f1_sym}")

# Function 2: x^3 - 1
f2_sym = x**3 - 1
derivative_f2_sym = sympy.diff(f2_sym, x)
print(f"\nOriginal function 2: g(x) = {f2_sym}")
print(f"First derivative of f2 with respect to x: g'(x) = {derivative_f2_sym}")

# You can also evaluate the symbolic derivative at a point
point_sym = 2
print(f"\nEvaluating derivative of f1 at x = {point_sym} (assuming k=some_value, here k is treated as a constant with respect to x): {derivative_f1_sym.subs(x, point_sym)}")
print(f"Evaluating derivative of f2 at x = {point_sym}: {derivative_f2_sym.subs(x, point_sym)}")

--- Symbolic Differentiation (using SymPy) ---
Original function 1: f(x) = -3*k + x**2
First derivative of f1 with respect to x: f'(x) = 2*x

Original function 2: g(x) = x**3 - 1
First derivative of f2 with respect to x: g'(x) = 3*x**2

Evaluating derivative of f1 at x = 2 (assuming k=some_value, here k is treated as a constant with respect to x): 4
Evaluating derivative of f2 at x = 2: 12


In [ ]:
import sympy

# Define the variables as symbols
x, n = sympy.symbols('x n')

# Function 3: (x^3 + 2x)^n
f3_sym = (x**3 + 2*x)**n
derivative_f3_sym = sympy.diff(f3_sym, x)
print(f"\nOriginal function 3: h(x) = {f3_sym}")
print(f"First derivative of h with respect to x: h'(x) = {derivative_f3_sym}")

# Example: evaluate for n=2, x=1
point_x = 1
point_n = 2
evaluated_derivative = derivative_f3_sym.subs({x: point_x, n: point_n})
print(f"\nEvaluating derivative of h at x = {point_x} and n = {point_n}: {evaluated_derivative}")


Original function 3: h(x) = (x**3 + 2*x)**n
First derivative of h with respect to x: h'(x) = n*(3*x**2 + 2)*(x**3 + 2*x)**n/(x**3 + 2*x)

Evaluating derivative of h at x = 1 and n = 2: 30


In [ ]:
import sympy

x, y = sympy.symbols('x y')

# Define the function
f_xy = sympy.sin(x*y) + sympy.cos(x+y)

print(f"Original function: f(x, y) = {f_xy}")

# Calculate partial derivative with respect to x
derivative_x = sympy.diff(f_xy, x)
print(f"\nPartial derivative with respect to x: ∂f/∂x = {derivative_x}")

# Calculate partial derivative with respect to y
derivative_y = sympy.diff(f_xy, y)
print(f"Partial derivative with respect to y: ∂f/∂y = {derivative_y}")

Original function: f(x, y) = sin(x*y) + cos(x + y)

Partial derivative with respect to x: ∂f/∂x = y*cos(x*y) - sin(x + y)
Partial derivative with respect to y: ∂f/∂y = x*cos(x*y) - sin(x + y)


In [ ]:
import sympy
x, y = sympy.symbols('x y')

f_xy1 = sympy.ln(x**2 + y**2 + 1)
f_xy2 = y*x**2 + sympy.exp(x*y)

der1 = sympy.diff(f_xy1, x)
der2 = sympy.diff(f_xy1, y)
der3 = sympy.diff(f_xy2, x)
der4 = sympy.diff(f_xy2, y)

# Use sympy.display or print to show all results
from IPython.display import display
display(der1, der2, der3, der4)

2*x/(x**2 + y**2 + 1)

2*y/(x**2 + y**2 + 1)

2*x*y + y*exp(x*y)

x**2 + x*exp(x*y)