<a href="https://colab.research.google.com/github/aadithya-vimal/SamsungInnovationCampus/blob/main/NumpyOperations_15_4_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd

data = np.genfromtxt('Emp_data.csv',
                     delimiter = ',',
                     skip_header = 1,
                     dtype = str)

print(data)

[['25' '50000' '2' 'IT' '3']
 ['30' '60000' '5' 'HR' '4']
 ['22' '45000' '1' 'IT' '2']
 ['35' '80000' '10' 'Finance' '5']
 ['28' '52000' '3' 'IT' '3']
 ['40' '90000' '12' 'Finance' '5']
 ['29' '58000' '4' 'HR' '4']
 ['31' '62000' '6' 'IT' '4']
 ['27' '48000' '2' 'Marketing' '3']
 ['45' '100000' '15' 'Finance' '5']
 ['38' '75000' '9' 'IT' '4']
 ['26' '51000' '3' 'Marketing' '3']
 ['33' '67000' '7' 'HR' '4']
 ['24' '47000' '1' 'IT' '2']
 ['36' '82000' '11' 'Finance' '5']
 ['32' '64000' '6' 'IT' '4']
 ['41' '91000' '13' 'Finance' '5']
 ['23' '46000' '1' 'Marketing' '2']
 ['37' '78000' '8' 'IT' '4']
 ['34' '72000' '7' 'HR' '4']
 ['39' '85000' '10' 'Finance' '5']
 ['21' '42000' '0' 'IT' '1']
 ['28' '53000' '3' 'Marketing' '3']
 ['42' '92000' '14' 'Finance' '5']
 ['30' '61000' '5' 'HR' '4']
 ['27' '49000' '2' 'IT' '3']
 ['35' '81000' '10' 'Finance' '5']
 ['29' '57000' '4' 'Marketing' '3']
 ['31' '63000' '6' 'IT' '4']
 ['44' '98000' '14' 'Finance' '5']
 ['36' '83000' '11' 'HR' '5']
 ['25' '51

In [24]:
#Extract numeric columns
age = data[:,0].astype(float)
salary = data[:,1].astype(float)
experience = data[:,2].astype(float)
performance = data[:,4].astype(float)

numeric_data = pd.DataFrame({
    'Age': age,
    'Salary': salary,
    'Experience': experience,
    'Performance': performance
})

print(numeric_data.head(20))

print(f"age: {age}")
print(f"salary: {salary}")
print(f"experience: {experience}")
print(f"performance: {performance}")

     Age    Salary  Experience  Performance
0   25.0   50000.0         2.0          3.0
1   30.0   60000.0         5.0          4.0
2   22.0   45000.0         1.0          2.0
3   35.0   80000.0        10.0          5.0
4   28.0   52000.0         3.0          3.0
5   40.0   90000.0        12.0          5.0
6   29.0   58000.0         4.0          4.0
7   31.0   62000.0         6.0          4.0
8   27.0   48000.0         2.0          3.0
9   45.0  100000.0        15.0          5.0
10  38.0   75000.0         9.0          4.0
11  26.0   51000.0         3.0          3.0
12  33.0   67000.0         7.0          4.0
13  24.0   47000.0         1.0          2.0
14  36.0   82000.0        11.0          5.0
15  32.0   64000.0         6.0          4.0
16  41.0   91000.0        13.0          5.0
17  23.0   46000.0         1.0          2.0
18  37.0   78000.0         8.0          4.0
19  34.0   72000.0         7.0          4.0
age: [25. 30. 22. 35. 28. 40. 29. 31. 27. 45. 38. 26. 33. 24. 36. 32. 41. 23

In [25]:
#Extracting categorical data
department = data[:,3]
print(f"department: {department}")

department: ['IT' 'HR' 'IT' 'Finance' 'IT' 'Finance' 'HR' 'IT' 'Marketing' 'Finance'
 'IT' 'Marketing' 'HR' 'IT' 'Finance' 'IT' 'Finance' 'Marketing' 'IT' 'HR'
 'Finance' 'IT' 'Marketing' 'Finance' 'HR' 'IT' 'Finance' 'Marketing' 'IT'
 'Finance' 'HR' 'IT' 'Marketing' 'Finance' 'IT' 'Finance' 'HR' 'IT'
 'Marketing' 'Finance' 'IT' 'Finance' 'Marketing' 'HR' 'Finance' 'IT'
 'Finance' 'IT' 'HR' 'Marketing']


In [27]:
#Summary statistics
print(f"Mean age: {np.mean(age)}")
print(f"Median salary: {np.median(salary)}")
print(f"Standard deviation of experience: {np.std(experience)}")
print(f"Minimum performance: {np.min(performance)}")
print(f"Maximum performance: {np.max(performance)}")

Mean age: 32.34
Median salary: 64500.0
Standard deviation of experience: 4.227339588914049
Minimum performance: 1.0
Maximum performance: 5.0


In [29]:
#Filtering salary
high_salary=data[salary>70000]
print(f"High salaries: {high_salary}")
print(f"Number of dimensions: {high_salary.ndim}")

High salaries: [['35' '80000' '10' 'Finance' '5']
 ['40' '90000' '12' 'Finance' '5']
 ['45' '100000' '15' 'Finance' '5']
 ['38' '75000' '9' 'IT' '4']
 ['36' '82000' '11' 'Finance' '5']
 ['41' '91000' '13' 'Finance' '5']
 ['37' '78000' '8' 'IT' '4']
 ['34' '72000' '7' 'HR' '4']
 ['39' '85000' '10' 'Finance' '5']
 ['42' '92000' '14' 'Finance' '5']
 ['35' '81000' '10' 'Finance' '5']
 ['44' '98000' '14' 'Finance' '5']
 ['36' '83000' '11' 'HR' '5']
 ['38' '76000' '9' 'Finance' '4']
 ['40' '89000' '12' 'Finance' '5']
 ['37' '79000' '8' 'IT' '4']
 ['34' '71000' '7' 'Marketing' '4']
 ['43' '95000' '13' 'Finance' '5']
 ['39' '86000' '10' 'Finance' '5']
 ['41' '93000' '13' 'Finance' '5']
 ['36' '84000' '11' 'Finance' '5']
 ['35' '80000' '10' 'HR' '5']]
Number of dimensions: 2


In [30]:
#Segmentation
filtered = data[(salary>70000) & (experience>5)]
print(f"Filtered data: {filtered}")

Filtered data: [['35' '80000' '10' 'Finance' '5']
 ['40' '90000' '12' 'Finance' '5']
 ['45' '100000' '15' 'Finance' '5']
 ['38' '75000' '9' 'IT' '4']
 ['36' '82000' '11' 'Finance' '5']
 ['41' '91000' '13' 'Finance' '5']
 ['37' '78000' '8' 'IT' '4']
 ['34' '72000' '7' 'HR' '4']
 ['39' '85000' '10' 'Finance' '5']
 ['42' '92000' '14' 'Finance' '5']
 ['35' '81000' '10' 'Finance' '5']
 ['44' '98000' '14' 'Finance' '5']
 ['36' '83000' '11' 'HR' '5']
 ['38' '76000' '9' 'Finance' '4']
 ['40' '89000' '12' 'Finance' '5']
 ['37' '79000' '8' 'IT' '4']
 ['34' '71000' '7' 'Marketing' '4']
 ['43' '95000' '13' 'Finance' '5']
 ['39' '86000' '10' 'Finance' '5']
 ['41' '93000' '13' 'Finance' '5']
 ['36' '84000' '11' 'Finance' '5']
 ['35' '80000' '10' 'HR' '5']]


In [32]:
#Dept-wise analysis
it_employees = data[department == 'IT']
print(f"IT employees: \n {it_employees}")

IT employees: 
 [['25' '50000' '2' 'IT' '3']
 ['22' '45000' '1' 'IT' '2']
 ['28' '52000' '3' 'IT' '3']
 ['31' '62000' '6' 'IT' '4']
 ['38' '75000' '9' 'IT' '4']
 ['24' '47000' '1' 'IT' '2']
 ['32' '64000' '6' 'IT' '4']
 ['37' '78000' '8' 'IT' '4']
 ['21' '42000' '0' 'IT' '1']
 ['27' '49000' '2' 'IT' '3']
 ['31' '63000' '6' 'IT' '4']
 ['25' '51000' '2' 'IT' '3']
 ['26' '52000' '3' 'IT' '3']
 ['37' '79000' '8' 'IT' '4']
 ['22' '44000' '1' 'IT' '2']
 ['24' '48000' '1' 'IT' '2']
 ['30' '60000' '5' 'IT' '4']]


In [37]:
#Outlier detection
outliers = salary[salary > 90000]
print(f"Salary outliers: \n {outliers}")

Salary outliers: 
 [100000.  91000.  92000.  98000.  95000.  93000.]


In [42]:
norm_salary = salary / np.linalg.norm(salary)
print(f"Normalized salaries: \n {norm_salary}")

Normalized salaries: 
 [0.10143908 0.12172689 0.09129517 0.16230253 0.10549664 0.18259034
 0.11766933 0.12578446 0.09738152 0.20287816 0.15215862 0.10346786
 0.13592837 0.09535273 0.16636009 0.12984202 0.18461912 0.09332395
 0.15824496 0.14607227 0.17244643 0.08520883 0.10752542 0.1866479
 0.12375568 0.0994103  0.16433131 0.11564055 0.12781324 0.19882059
 0.16838887 0.10346786 0.13795715 0.1541874  0.10549664 0.18056156
 0.1095542  0.16027374 0.14404349 0.19273425 0.08926639 0.17447522
 0.10143908 0.1318708  0.18867669 0.09738152 0.17041765 0.12172689
 0.16230253 0.11361177]


In [44]:
#Coefficient of correlation
corr = np.corrcoef(experience, salary)
print(f"Correlation coefficient: \n {corr}")

Correlation coefficient: 
 [[1.         0.99211731]
 [0.99211731 1.        ]]


In [47]:
#New feature creation
salary_per_year = salary / (experience + 1)
print(f"Salary per year: \n {salary_per_year}")

Salary per year: 
 [16666.66666667 10000.         22500.          7272.72727273
 13000.          6923.07692308 11600.          8857.14285714
 16000.          6250.          7500.         12750.
  8375.         23500.          6833.33333333  9142.85714286
  6500.         23000.          8666.66666667  9000.
  7727.27272727 42000.         13250.          6133.33333333
 10166.66666667 16333.33333333  7363.63636364 11400.
  9000.          6533.33333333  6916.66666667 17000.
  8500.          7600.         13000.          6846.15384615
 13500.          8777.77777778  8875.          6785.71428571
 22000.          7818.18181818 16666.66666667  9285.71428571
  6642.85714286 24000.          7000.         10000.
  7272.72727273 11200.        ]


In [49]:
#Reshaping for ML algorithm
X = np.column_stack((age, experience))
Y = salary
print(f"X: \n {X}")
print(f"Y: \n {Y}")

X: 
 [[25.  2.]
 [30.  5.]
 [22.  1.]
 [35. 10.]
 [28.  3.]
 [40. 12.]
 [29.  4.]
 [31.  6.]
 [27.  2.]
 [45. 15.]
 [38.  9.]
 [26.  3.]
 [33.  7.]
 [24.  1.]
 [36. 11.]
 [32.  6.]
 [41. 13.]
 [23.  1.]
 [37.  8.]
 [34.  7.]
 [39. 10.]
 [21.  0.]
 [28.  3.]
 [42. 14.]
 [30.  5.]
 [27.  2.]
 [35. 10.]
 [29.  4.]
 [31.  6.]
 [44. 14.]
 [36. 11.]
 [25.  2.]
 [33.  7.]
 [38.  9.]
 [26.  3.]
 [40. 12.]
 [28.  3.]
 [37.  8.]
 [34.  7.]
 [43. 13.]
 [22.  1.]
 [39. 10.]
 [27.  2.]
 [32.  6.]
 [41. 13.]
 [24.  1.]
 [36. 11.]
 [30.  5.]
 [35. 10.]
 [29.  4.]]
Y: 
 [ 50000.  60000.  45000.  80000.  52000.  90000.  58000.  62000.  48000.
 100000.  75000.  51000.  67000.  47000.  82000.  64000.  91000.  46000.
  78000.  72000.  85000.  42000.  53000.  92000.  61000.  49000.  81000.
  57000.  63000.  98000.  83000.  51000.  68000.  76000.  52000.  89000.
  54000.  79000.  71000.  95000.  44000.  86000.  50000.  65000.  93000.
  48000.  84000.  60000.  80000.  56000.]
