<a href="https://colab.research.google.com/github/aadithya-vimal/SamsungInnovationCampus/blob/main/NumpyBasics_13_4_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,3,5,7])
arr2=arr
print(id(arr))
print(id(arr2))

132510467713200
132510467713200


In [ ]:
#creating an array using a tuple
arr3=np.array((1,2,3,4))
print(arr3)
#creating a array using a dictionary with key value pairs
arr4=np.array({1:'a',2:'b',3:'c'})
print(arr4)
#creating a array using a set
arr5=np.array({1,2,3,4})
print(arr5)
#using range function in arrays
arr6=np.array(range(1,10))
print(arr6)
len10=np.arange(10)   #creates an array in sequential order
len(len10)
len10.size
arr7=np.arange(1,5,0.2)
print(arr7)
id(arr7)
arr7=np.array([[1,2],[2,4],[4,6]])
print(len(arr7))   #len is a function
print(arr7.size)
print(arr7.shape)   #returns in the form of a tuple
print(arr7.ndim)

[1 2 3 4]
{1: 'a', 2: 'b', 3: 'c'}
{1, 2, 3, 4}
[1 2 3 4 5 6 7 8 9]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]
3
6
(3, 2)
2


In [ ]:
#create a 3D array and check the size and shape of it
arr8=np.array([[[1,2],[3,4],[4,5]],[[2,1],[3,6],[2,8]]])
print(arr8.size)
print(arr8.shape)

12
(2, 3, 2)


In [ ]:
diff=np.array(['hhgfjh', 4356, 456.35])
print(diff)
print(type(diff))
print(type(diff[0]))

['hhgfjh' '4356' '456.35']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [ ]:
print(np.linspace(1,20,5)) #(start,end,no.of pts)
print(np.zeros(5))  #default d.t. is float
print(np.ones(4))

[ 1.    5.75 10.5  15.25 20.  ]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [ ]:
toarr = ([[1,2],[3,4],[5,6]])
print(np.array(toarr))
print(toarr[0][1])
np.ndim(toarr)

[[1 2]
 [3 4]
 [5 6]]
2


2

In [ ]:
trarr=np.array([[[1,2],[3,4],[4,5]],[[2,1],[3,6],[2,8]]])
print(trarr)
print(trarr[0][1][1])

[[[1 2]
  [3 4]
  [4 5]]

 [[2 1]
  [3 6]
  [2 8]]]
4


In [ ]:
print(np.zeros((2,2)))
print(np.ones((2,4), dtype='int64'))

[[0. 0.]
 [0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]


In [ ]:
trarr.astype('str')

array([[['1', '2'],
        ['3', '4'],
        ['4', '5']],

       [['2', '1'],
        ['3', '6'],
        ['2', '8']]], dtype='<U21')

In [ ]:
print(trarr.reshape(4,3))    #if the change is not assigned, it is a temporary change
 #or
trarr.shape=(3,4)
print(trarr)

[[1 2 3]
 [4 4 5]
 [2 1 3]
 [6 2 8]]
[[1 2 3 4]
 [4 5 2 1]
 [3 6 2 8]]


In [ ]:
print(np.random.rand(1,5))
print(np.random.randint(1,5,3))
print(np.random.randn(2,3))

[[0.49947353 0.27925986 0.24738021 0.97235157 0.52499557]]
[1 3 3]
[[-1.20177779  1.45660673 -0.34466101]
 [-1.09979611  0.46927805  0.91503664]]


In [ ]:
%time for i in range(1000): np.arange(1000000)*2

%time for i in range(1000): list(range(1000000))*2

CPU times: user 1.83 s, sys: 17.9 ms, total: 1.85 s
Wall time: 1.87 s
CPU times: user 52.7 s, sys: 22 s, total: 1min 14s
Wall time: 1min 15s


In [ ]:
a= np.array([1,2,3])
b=np.append(a,[4,5,6])
print(b)
np.delete(b,0)

[1 2 3 4 5 6]


array([2, 3, 4, 5, 6])

In [ ]:
c= np.array([[1,2],[3,4],[5,6]])
d=np.append(c,[[7,8]],axis=0)
print(d)
new_columns = np.array([[7, 8]] * d.shape[0])
e=np.append(d, new_columns, axis=1)
print(e)
print(np.delete(e,0,axis=0))
np.delete(e,1,axis=1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 7 8]
 [3 4 7 8]
 [5 6 7 8]
 [7 8 7 8]]
[[3 4 7 8]
 [5 6 7 8]
 [7 8 7 8]]


array([[1, 7, 8],
       [3, 7, 8],
       [5, 7, 8],
       [7, 7, 8]])